version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/worktohome
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - worktohome-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - worktohome-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=worktohome
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - worktohome-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - worktohome-network

volumes:
  postgres_data:

networks:
  worktohome-network:
    driver: bridge
